- LICENSE
- README.md
- SPEAKER_GUIDE.md
- SPONSOR_GUIDE.md
- helsinki/README.md
- tampere/README.md
This basically adds all of https://github.com/cloud-native-finland/meetups' material :smile:
Fixes #1
> Add Kubernetes Finland material

- MEETUP_DETAILS.md
- UPDATE_RSVP.md
@kaspernissen We can iterate on these later, but adding them here to have some kind of base.
> Add some communication texts

- .gitattributes
First step of #11. I will merge this now to unblock the migration.
cc @kaspernissen
> Track large files with Git LFS

- Makefile
- generator/templates.go
- generator/templates_test.go
- generator/testdata/1/helsinki.md
- generator/testdata/2/in.yaml
- generator/testdata/2/tampere.md
- helsinki/README.md
- meetups.yaml
I made some small code changes:
- "Recording" was missing in the template from presentation
- Linebreak added for multiple meetups.
We probably need a new issue for "Presentation speaker should be array field"
> Helsinki meetups

- .travis.yml
- Makefile
- helsinki/README.md
- tampere/README.md
This PR
- Fixes some generator differences at HEAD
- Adds Travis CI integration for PRs so we can see if things are up-to-date or not
- Enables Go modules unconditionally
This PR passes the CI tests, I'll go ahead and merge
> Travis CI integration

- Makefile
> Fix makefile to build for host os/arch

- generator/templates.go
- generator/types.go
- meetups.yaml
> Add support for multiple speakers

- generator/types.go
This PR improves the error handling when a speaker reference is wrong.
> add better error handling when speaker references is not found

- companies.yaml
- speakers.yaml
- stockholm/README.md
- stockholm/meetup.yaml
resolve https://github.com/cloud-native-nordics/meetups/issues/32
> add Stockholm meetup

- speakers.yaml
- tampere/README.md
- tampere/meetup.yaml
> Adds April Kubernetes Meetup Tampere

- aarhus/README.md
- aarhus/meetup.yaml
This PR adds the meetup "Cloud Native Aarhus Hack Nights #2: Prometheus
> add Aarhus Hack Nights 2 meetup to readme

- aarhus/README.md
- aarhus/meetup.yaml
- config.json
- copenhagen/meetup.yaml
- generator/templates.go
- generator/types.go
- helsinki/README.md
- helsinki/meetup.yaml
- tampere/README.md
- tampere/meetup.yaml
Call for proposals added. Links too meet up group`s website.
@luxas
> Add CFP field to MeetupGroup

- aarhus/README.md
- aarhus/meetup.yaml
- companies.yaml
- config.json
- copenhagen/README.md
- copenhagen/meetup.yaml
- helsinki/meetup.yaml
Next meetups now using the generator :muscle:
> Next meetups

- aarhus/README.md
- aarhus/meetup.yaml
- config.json
- copenhagen/README.md
- copenhagen/meetup.yaml
- generator/main.go
- generator/meetup.go
- generator/templates_test.go
- generator/testdata/1/companies.yaml
- generator/testdata/1/config.json
- generator/testdata/1/helsinki/README.md
- generator/testdata/1/helsinki/meetup.yaml
- generator/testdata/1/speakers.yaml
- generator/testdata/2/companies.yaml
- generator/testdata/2/config.json
- generator/testdata/2/speakers.yaml
- generator/testdata/2/tampere/README.md
- generator/testdata/2/tampere/meetup.yaml
- generator/types.go
- helsinki/meetup.yaml
- stockholm/meetup.yaml
- tampere/meetup.yaml
cc @kaspernissen @netumoliver 
This improves the UX for writing the YAML files, and lets the user only think about how long a presentation took.
> Switch from hard-coded timestamps to delay/duration for presentations

- aarhus/meetup.yaml
- config.json
- copenhagen/README.md
- copenhagen/meetup.yaml
- stats.json
This PR just updates the stats and meetup information with the latest data.
> Update stats and meetup information

- README.md
- aalborg/README.md
- aalborg/meetup.yaml
- companies.yaml
- config.json
- speakers.yaml
by adding:
- company to company.yaml, 
- speakers/organizers to speakers.yaml 
and:
- create folder for aalborg
- create a meetup.yaml inside that folder
everything else generated by "make" operation
> added aalborg meetup

- MEETUP_DETAILS.md
- aalborg/README.md
- aalborg/meetup.yaml
- aarhus/README.md
- aarhus/meetup.yaml
- companies.yaml
- config.json
- göteborg/README.md
- göteborg/meetup.yaml
- helsinki/README.md
- helsinki/meetup.yaml
- speakers.yaml
- tampere/README.md
- tampere/meetup.yaml
slides links will be added soon
> August meetup Tampere

- aalborg/README.md
- aalborg/meetup.yaml
- config.json
Add initial meetup from Aalborg Denmark
> add info from initial meetup in Aalborg Denmark

- aarhus/README.md
- aarhus/meetup.yaml
- companies.yaml
- config.json
- generator/meetup.go
- generator/types.go
- helsinki/README.md
- helsinki/meetup.yaml
- speakers.yaml
- stockholm/README.md
- stockholm/meetup.yaml
- tampere/README.md
- tampere/meetup.yaml
- turku/README.md
- turku/meetup.yaml
Work in progress as I am still missing all the slides.
> Update Aarhus meetups

- aalborg/README.md
- aalborg/meetup.yaml
- autogenerated/helsinki.yaml
- config.json
Added information from second meetup in Aalborg 😃
> Add cncf aalborg meetup 2

- bergen/meetup.yaml
- speakers.yaml
Add the Meetup agenda for for Cloud Native Bergen meetup.
> Add agenda for Cloud Native Bergen

- README.md
- bergen/README.md
- bergen/meetup.yaml
- config.json
- copenhagen/README.md
- generator/types.go
- speakers.yaml
- stats.json
> Better error messages when unmarshalling speakers and companies

- aalborg/README.md
- aarhus/README.md
- bergen/README.md
- copenhagen/README.md
- generator/templates.go
- göteborg/README.md
- helsinki/README.md
- oslo/README.md
- reykjavík/README.md
- stockholm/README.md
- tampere/README.md
- turku/README.md
- umeå/README.md
This PR adds the description information and meetup picture to `*/README.md`
> [generator] Add pictures and descriptions to the meetup Markdown file

- README.md
- aarhus/README.md
- config.json
- copenhagen/README.md
- copenhagen/meetup.yaml
- speakers.yaml
- stats.json
> Update company for hans.duedal

- aarhus/README.md
- companies.yaml
- config.json
- göteborg/README.md
- helsinki/README.md
- helsinki/meetup.yaml
- speakers.yaml
- stats.json
cc @LinAnt @netumoliver @Ani000 @kaspernissen
> Add Helsinki November agenda

- aarhus/README.md
- aarhus/meetup.yaml
- config.json
- helsinki/README.md
- stats.json
@hoeghh do you have slides for your talk?
> Update agendas for Aarhus

- docs/MEETUP_TYPES.md
- stats.json
Added some more descriptions on the different types
> Add initial descriptions on different a couple of different meetup types
